# Generated by Django 3.2.8 on 2022-11-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insecureApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='user_id',
        ),
    ]
